### ISSUE TITLE
Regression issue in Prost 0.14.3

### ISSUE THREAD

**Issue by sunng87** [tokio-rs/prost#1390]
We get error like this when use Prost 0.14.3. This `VecVisitor` is a symbol generated from derive macro but it seems prost is trying to locate it under wrong module `prost::alloc::vec`.

```
error[E0405]: cannot find trait `VecVisitor` in module `prost::alloc::vec`
  --> /home/nsun/.cargo/git/checkouts/otel-arrow-a8e04c198cb1dc9e/452821e/rust/otel-arrow-rust/src/proto/././opentelemetry.proto.trace.v1.rs:32:10
   |
32 | #[derive(crate::pdata::otlp::Message)]
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `prost::alloc::vec`
   |
   = note: this error originates in the derive macro `crate::pdata::otlp::Message` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0405]: cannot find trait `i32Visitor` in this scope
  --> /home/nsun/.cargo/git/checkouts/otel-arrow-a8e04c198cb1dc9e/452821e/rust/otel-arrow-rust/src/proto/././opentelemetry.proto.trace.v1.rs:32:10
   |
32 | #[derive(crate::pdata::otlp::Message)]
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
   |
   = note: this error originates in the derive macro `crate::pdata::otlp::Message` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0422]: cannot find struct, variant or union type `VecEncodedLen` in module `prost::alloc::vec`
  --> /home/nsun/.cargo/git/checkouts/otel-arrow-a8e04c198cb1dc9e/452821e/rust/otel-arrow-rust/src/proto/././opentelemetry.proto.trace.v1.rs:32:10
   |
32 | #[derive(crate::pdata::otlp::Message)]
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `prost::alloc::vec`
   |
   = note: this error originates in the derive macro `crate::pdata::otlp::Message` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0422]: cannot find struct, variant or union type `i32EncodedLen` in this scope
  --> /home/nsun/.cargo/git/checkouts/otel-arrow-a8e04c198cb1dc9e/452821e/rust/otel-arrow-rust/src/proto/././opentelemetry.proto.trace.v1.rs:32:10
   |
32 | #[derive(crate::pdata::otlp::Message)]
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
   |
   = note: this error originates in the derive macro `crate::pdata::otlp::Message` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0405]: cannot find trait `VecVisitor` in module `prost::alloc::vec`
  --> /home/nsun/.cargo/git/checkouts/otel-arrow-a8e04c198cb1dc9e/452821e/rust/otel-arrow-rust/src/proto/././opentelemetry.proto.trace.v1.rs:84:14
   |
84 |     #[derive(crate::pdata::otlp::Message)]
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `prost::alloc::vec`
   |
   = note: this error originates in the derive macro `crate::pdata::otlp::Message` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0422]: cannot find struct, variant or union type `VecEncodedLen` in module `prost::alloc::vec`
  --> /home/nsun/.cargo/git/checkouts/otel-arrow-a8e04c198cb1dc9e/452821e/rust/otel-arrow-rust/src/proto/././opentelemetry.proto.trace.v1.rs:84:14
   |
84 |     #[derive(crate::pdata::otlp::Message)]
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `prost::alloc::vec`
   |
   = note: this error originates in the derive macro `crate::pdata::otlp::Message` (in Nightly builds, run with -Z macro-backtrace for more info)
```

The same code compiles on Prost 0.14.1.

The reproducible code is at https://github.com/GreptimeTeam/otel-arrow/tree/5da284414e9b14f678344b51e5292229e4b5f8d2#

Steps to reproduce:

```
git clone https://github.com/GreptimeTeam/otel-arrow.git
git checkout 5da284414e9b14f678344b51e5292229e4b5f8d2
cd rust/otel-arrow-rust
cargo build
```

It passes only when we pin prost to 0.14.1
