### PR TITLE
fix(prost-build): re-export `error_message_protoc_not_found`, `protoc_from_env` & `protoc_include_from_env`

### PR DESCRIPTION
**Pull request by eopb**
fixes: #1062

I'm adding this to fix a breaking change introduced in https://github.com/tokio-rs/prost/pull/1020 where these items were moved.

Since `0.12.5` this is causing build failures after `cargo update`.

```
   Compiling grpc-build v6.1.0
error[E0432]: unresolved imports `prost_build::protoc_from_env`, `prost_build::protoc_include_from_env`
 --> /Users/ethan.brierley/.cargo/registry/src/index.crates.io-6f17d22bba15001f/grpc-build-6.1.0/src/lib.rs:3:19
  |
3 | use prost_build::{protoc_from_env, protoc_include_from_env, Module};
  |                   ^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^^^ no `protoc_include_from_env` in the root
  |                   |
  |                   no `protoc_from_env` in the root
```

### CODE REVIEW

**Comment by eopb** [comment]
@gibbz00 
Looking at #1015 I'm guessing that making these private was intentional. I'm guessing this was expected to be included only in a breaking release. If you'd like these to be private you can open a follow-up PR deprecating the re-exports so that the change remains non-breaking. The re-exports can then be removed in `0.13.0`.

**Comment by LucioFranco** [comment]
Yup, let me yank v0.12.5, we didn't think this was going to cause an issue but clearly it does 😄 thanks for the report.

**Comment by LucioFranco** [comment]
It's been yanked, we will work on a follow up release that fixes these semver issues.

File: prost-build/src/lib.rs [hunk 1]
```diff
@@ -149,7 +149,7 @@ mod message_graph;
 mod path;
 
 mod config;
-pub use config::Config;
+pub use config::{protoc_from_env, protoc_include_from_env, Config};
```
Comment (caspermeijn) [inline prost-build/src/lib.rs:152]: We should restore all move `pub` functions. This version will satisfy cargo-semver-checks:

```suggestion
pub use config::{error_message_protoc_not_found, protoc_from_env, protoc_include_from_env, Config};
```

**Review by caspermeijn — CHANGES_REQUESTED** [review]
Sorry, I accepted the change that broke your build. I was naive of me to assume this is an “internal” function and nobody is using it.

File: prost-build/src/lib.rs (hunk 1 above)
Comment (eopb) [reply prost-build/src/lib.rs]: > Sorry, I accepted the change that broke your build. I was naive of me to assume this is an “internal” function and nobody is using it.

No worries. It was great to see it quickly yanked and sorted :raised_hands:. Thanks for spending your time working on the crates I use :)

> We should restore all moved pub functions. This version will satisfy cargo-semver-checks:

:+1: https://github.com/tokio-rs/prost/compare/1e5e904b47773b92ea46ba6e82feaaa2f006a9f4..f4be7b750a6039c8535ae3e105cf912c3b0c12e7

Comment (caspermeijn) [reply prost-build/src/lib.rs]: > No worries. It was great to see it quickly yanked and sorted 🙌. Thanks for spending your time working on the crates I use :)

Well, you created this PR half an hour after publish. So, I am impressed with that as well :smiley:

**Review by caspermeijn — APPROVED** [review]
