### PR TITLE
Fix bug on codegen in ::prost::Enumeration

### LINKED ISSUE #927: Bug on codegen in ::prost::Enumeration
```
error[E0119]: conflicting implementations of trait `TryFrom<i32>` for type `grpc_codegen::Action`
   --> /Users/bapperson/Code/MyProjects/valorem/trade-api/target/debug/build/mycodegen/out/mycodegen.v1.rs:341:68
    |
341 | #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    |                                                                    ^^^^^^^^^^^^^^^^^^^^
    |
    = note: conflicting implementation in crate `core`:
            - impl<T, U> TryFrom<U> for T
              where U: Into<T>;
    = note: this error originates in the derive macro `::prost::Enumeration` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Using tonic 0.10.1 and prost-types/prost 0.12.1, on building codegen for proto with an enumeration defined:

```
enum ItemType {
    NATIVE = 0;
    ERC20 = 1;
    ERC721 = 2;
    ERC1155 = 3;
    ERC721_WITH_CRITERIA = 4;
    ERC1155_WITH_CRITERIA = 5;
}```

I see this bug, which prevents build from succeeding. This appears to be a regression in 0.9.2->0.10.1 tonic and 0.11.9 prost.

This was also noted in #812 in a recent comment.

### PR DESCRIPTION
**Pull request by megsdevs**
Fixes #927 and #812, caused by #853. 

Reverting the changes until a working implementation + test(s) have been built.

I encourage @Leulz to address this before bringing it back in.

### CODE REVIEW

**Comment by megsdevs** [comment]
draft until resolved compatibility with current version of tonic

**Comment by megsdevs** [comment]
This uncovered another bug with codegen where all message data structures are not implementing the `Message` trait with the expected path. An example:

```
error[E0277]: the trait bound `grpc_codegen::Empty: prost::message::Message` is not satisfied
    --> /Users/megan/git/trade-api/target/debug/build/valorem-trade-9bf8c220466cd8d7/out/valorem.trade.v1.rs:1706:65
     |
1706 |                         let mut grpc = tonic::server::Grpc::new(codec)
     |                                        ------------------------ ^^^^^ the trait `prost::message::Message` is not implemented for `grpc_codegen::Empty`
     |                                        |
     |                                        required by a bound introduced by this call
     |
     = help: the following other types implement trait `prost::message::Message`:
               bool
               i32
               i64
               u32
               u64
               f32
               f64
               prost_types::compiler::Version
             and 76 others
     = note: required for `ProstCodec<FeeStructure, grpc_codegen::Empty>` to implement `Codec`
```

Open to suggestions on how to resolve this
