### PR TITLE
Fixes: #905, fix: Use full path of Result type

### LINKED ISSUE #905: Type error regression when using enum called Result
I am working on a project that uses Prost (via Tonic) to compile a protobuf file for use with gRPC. The file compiles fine with prost 0.11.9, but when switching to prost 0.12.0 the generated Rust file contains type errors.

The minimal protobuf file required to reproduce the problem is this one:

```proto
syntax = "proto3";

package fail;

enum Result {
  HELLO = 0;
}

message FailMessage {
  Result result = 1;
}
```

When attempting to compile the generated rust file the following errors are returned:

```
error[E0107]: enum takes 0 generic arguments but 2 generic arguments were supplied
 --> /private/tmp/tonicfail/target/debug/build/tonicfail-ca0c3cb604ffea00/out/fail.rs:2:28
  |
2 | #[derive(Clone, PartialEq, ::prost::Message)]
  |                            ^^^^^^^^^^^^^^^^- help: remove these generics
  |                            |
  |                            expected 0 generic arguments
  |
note: enum defined here, with 0 generic parameters
 --> /private/tmp/tonicfail/target/debug/build/tonicfail-ca0c3cb604ffea00/out/fail.rs:9:10
  |
9 | pub enum Result {
  |          ^^^^^^
  = note: this error originates in the derive macro `::prost::Message` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
   --> /private/tmp/tonicfail/target/debug/build/tonicfail-ca0c3cb604ffea00/out/fail.rs:2:28
    |
2   | #[derive(Clone, PartialEq, ::prost::Message)]
    |                            ^^^^^^^^^^^^^^^^
    |                            |
    |                            expected `Result`, found `Result<_, _>`
    |                            expected due to this
    |
    = note: `std::result::Result<_, _>` and `proto::Result` have similar names, but are actually distinct types
note: `std::result::Result<_, _>` is defined in crate `core`
   --> /Users/djinn/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:502:1
    |
502 | pub enum Result<T, E> {
    | ^^^^^^^^^^^^^^^^^^^^^
note: `proto::Result` is defined in the current crate
   --> /private/tmp/tonicfail/target/debug/build/tonicfail-ca0c3cb604ffea00/out/fail.rs:9:1
    |
9   | pub enum Result {
    | ^^^^^^^^^^^^^^^
    = note: this error originates in the derive macro `::prost::Message` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
   --> /private/tmp/tonicfail/target/debug/build/tonicfail-ca0c3cb604ffea00/out/fail.rs:2:28
    |
2   | #[derive(Clone, PartialEq, ::prost::Message)]
    |                            ^^^^^^^^^^^^^^^^
    |                            |
    |                            expected `Result`, found `Result<_, _>`
    |                            this expression has type `proto::Result`
    |
    = note: `std::result::Result<_, _>` and `proto::Result` have similar names, but are actually distinct types
note: `std::result::Result<_, _>` is defined in crate `core`
   --> /Users/djinn/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:502:1
    |
502 | pub enum Result<T, E> {
    | ^^^^^^^^^^^^^^^^^^^^^
note: `proto::Result` is defined in the current crate
   --> /private/tmp/tonicfail/target/debug/build/tonicfail-ca0c3cb604ffea00/out/fail.rs:9:1
    |
9   | pub enum Result {
    | ^^^^^^^^^^^^^^^
    = note: this error originates in the derive macro `::prost::Message` (in Nightly builds, run with -Z macro-backtrace for more info)

Some errors have detailed explanations: E0107, E0308.
For more information about an error, try `rustc --explain E0107`.
error: could not compile `tonicfail` (bin "tonicfail") due to 3 previous errors
```

If desired I can provide a minimal Rust project that demonstrates the failed compilation.

### PR DESCRIPTION
**Pull request by anstylian**
in case you are interested in unit test, please let me know

### CODE REVIEW

**Comment by c0mm4nd** [comment]
Thank you anstylian, I'm using your prost fork with [the latest tonic](https://github.com/hyperium/tonic). Your fork help me fix the Result mismatch problem, but there are some additional bugs as below:

```
error[E0277]: the trait bound `AssetIssueContract: prost::message::Message` is not satisfied
     --> src/protocol.rs:17676:30
      |
17676 | ...                   .apply_compression_config(
      |                        ^^^^^^^^^^^^^^^^^^^^^^^^ the trait `prost::message::Message` is not implemented for `AssetIssueContract`
      |
      = help: the following other types implement trait `prost::message::Message`:
                bool
                i32
                i64
                u32
                u64
                f32
                f64
                Box<M>
              and 4 others
      = note: required for `ProstCodec<AssetIssueContract, BytesMessage>` to implement `Codec`
note: required by a bound in `tonic::server::Grpc::<T>::apply_compression_config`
     --> /mnt/workspace/lab0/.cargo/git/checkouts/tonic-54a04bc36763b24d/79246e7/tonic/src/server/grpc.rs:46:8
      |
46    |     T: Codec,
      |        ^^^^^ required by this bound in `Grpc::<T>::apply_compression_config`
...
183   |     pub fn apply_compression_config(
      |            ------------------------ required by a bound in this associated function

error[E0277]: the trait bound `BytesMessage: prost::message::Message` is not satisfied
     --> src/protocol.rs:17676:30
      |
17676 | ...                   .apply_compression_config(
      |                        ^^^^^^^^^^^^^^^^^^^^^^^^ the trait `prost::message::Message` is not implemented for `BytesMessage`
      |
      = help: the following other types implement trait `prost::message::Message`:
                bool
                i32
                i64
                u32
                u64
                f32
                f64
                Box<M>
              and 4 others
      = note: required for `ProstCodec<AssetIssueContract, BytesMessage>` to implement `Codec`
note: required by a bound in `tonic::server::Grpc::<T>::apply_compression_config`
     --> /mnt/workspace/lab0/.cargo/git/checkouts/tonic-54a04bc36763b24d/79246e7/tonic/src/server/grpc.rs:46:8
      |
46    |     T: Codec,
      |        ^^^^^ required by this bound in `Grpc::<T>::apply_compression_config`
...
183   |     pub fn apply_compression_config(
      |            ------------------------ required by a bound in this associated function
```
